const USER_CREATE = "USER_CREATE";
const USER_AUTHENTICATE = "USER_AUTHENTICATE";
const SUBMIT_BUY_ORDER = "SUBMIT_BUY_ORDER";
const SUBMIT_SELL_ORDER = "SUBMIT_SELL_ORDER";
const DEPOSIT_FUNDS = "DEPOSIT_FUNDS";
const WITHDRAW_FUNDS = "WITHDRAW_FUNDS";
const PORT = 3000;

const PORT = (module.exports = {
  USER_CREATE,
  USER_AUTHENTICATE,
  SUBMIT_BUY_ORDER,
  SUBMIT_SELL_ORDER,
  DEPOSIT_FUNDS,
  WITHDRAW_FUNDS,
  PORT,
});
